config/routes.rb
Virturlmin::Application.routes.draw do
 
  mount Ckeditor::Engine => '/ckeditor'

  resources :users  do
      collection do
        get :domain
        put :domain
        get :password 
        put :password 
      end
    end

  resources :blogs

  resources :files   do
      collection do
        get :zip
        get :unzip
        get :logout
        post :setlocale
      end
    end
 resources :sessions do
      collection do
        get :home
        get :yinsi
        get :logout
        post :setlocale
      end
    end
  resources :tops do
        collection do
        get :resume
        get :logout
        post :setlocale
      end
  end
  namespace :admin do 
    match '/',:controller => 'sessions',:action => 'new'
    resources :sessions do
      collection do
        get :home
        get :logout
        post :setlocale
      end
    end
    resources :administrators
    resources :categories
    resources :blogs
    resources :links
    resources :pages
  end

  root :to => "sessions#new"

match '/files/master/*file' => 'files#index' , :constraints => { :file => /.*/  } , :format => false
match '/files/zip/*file' => 'files#zip' , :constraints => { :file => /.*/  } , :format => false
match '/files/unzip/*file' => 'files#unzip' , :constraints => { :file => /.*/  } , :format => false
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  password   :string(255)
#  domain     :string(255)
#  start_date :datetime
#  end_data   :datetime
#  price      :integer
#  f          :string(255)
#  last_login :datetime
#  created_at :datetime         not null
#  updated_at :datetime         not null
#


class User < ActiveRecord::Base
  extend ActiveModel::Callbacks
    validates :name   ,:presence => true  ,:uniqueness  => true , :format => { :with => /[a-z]{4,}/i }
    validates :domain   ,:presence => true  ,:uniqueness  => true
    validates :password, :confirmation => true ,:presence => true 
 

    attr_accessible :name, :password, :password_confirmation ,:domain , :qq ,:tel , :email ,:domain2  ,:presence => true



end

app/controllers/users_controller.rb
# coding: UTF-8
class UsersController < ApplicationController
  # GE: /Users
  # GET /Users.xml
   before_filter :user_authorize
   skip_before_filter :user_authorize, :only => [:new, :create]

  def index
    @user = User.find_by_name(  session[:user_name] )
 
  end

  # # GET /Users/1
  # # GET /Users/1.xml
  # def show
  #   @user = User.find(params[:id])
 
  #   respond_to do |format|
  #     format.html # show.html.erb
  #     format.xml  { render :xml => @user }
  #   end
  # end

  # GET /Users/new
  # GET /Users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /Users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /Users
  # POST /Users.xml
  def create
    @user = User.new(params[:user])

    # render :update do |page|
    #   if @user.save
    #     page.alert('sucess create')
    #   else
    #     page.alert(@user.errors.full_messages.join("\n"))
    #   end
    # end

       respond_to do |format|
         if @user.save
          session[:user_name] =  @user.name
# create user
p system("useradd -m #{@user.name} -s /bin/bash  ")
p system("passwd #{@user.name} <<EOF
#{@user.password}
#{@user.password}
EOF")
# create mysql
p system(
" mysql -uroot -p123456 -e\"
CREATE USER '#{@user.name}'@'%' IDENTIFIED BY  '#{@user.password}';
GRANT USAGE ON * . * TO  '#{@user.name}'@'%' IDENTIFIED BY  '#{@user.name}' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;
CREATE DATABASE IF NOT EXISTS  #{@user.name} ;
GRANT ALL PRIVILEGES ON  #{@user.name}.* TO  '#{@user.name}'@'%'  IDENTIFIED BY  '#{@user.password}';
\"
")

# # create nginx
File.open("/opt/nginx/conf/website/#{@user.name}.conf", "w") do |file|
file.write(
   " server {
        listen       80;
        server_name   #{@user.domain} #{@user.domain2};

      location / {
        root   /home/#{@user.name}/www;

        access_log /root/#{@user.name}.log;
        error_log  /root/#{@user.name}.log;

        index  index.php index.html index.htm;
        }

       location ~ \.php$ {
            root   /home/#{@user.name}/www;
            index  index.php index.html index.htm;
            fastcgi_pass   127.0.0.1:9000;
            fastcgi_index  index.php;
        #    fastcgi_param  SCRIPT_FILEnAME  /scripts$fastcgi_script_name;
            fastcgi_param  SCRIPT_FILENAME  /home/#{@user.name}/www$fastcgi_script_name;
            fastcgi_param SCRIPT_NAME /home/#{@user.name}/www$fastcgi_script_name;
            include        fastcgi_params;
       }

    }
    "
)
end

           format.html { redirect_to(@user, :notice => 'User was successfully created.') }
           format.xml  { render :xml => @user, :status => :created, :location => @user }
         else
           format.html { render :action => "new" }
           format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
         end
       end
  end

  # PUT /Users/1
  # PUT /Users/1.xml
  def update
        @user = User.find_by_name(session[:user_name])
        params[:user].delete('name')
        params[:user].delete('domain')
 
   respond_to do |format|
     if @user.update_attributes(params[:user])
       format.html { redirect_to(users_path, :notice => '保存成功') }
       format.xml  { head :ok }
     else
       format.html { render :action => "edit" ,:notice => '保存11111'  }
       format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
     end
   end
  end


  def password
        @user = User.find_by_name(session[:user_name])

  if request.put?
   params[:user].delete('name')
   params[:user].delete('domain')
   respond_to do |format|
     if @user.update_attributes(params[:user])

      p system("passwd #{@user.name} <<EOF
#{@user.password}
#{@user.password}
EOF")
      flash[:notice] = '修改成功!'
       format.html { redirect_to(users_path) }
       format.xml  { head :ok }
     else
       flash[:notice] = '修改失败!'
       format.html { redirect_to(users_path) }
       format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
     end
   end
 end

  end

  def domain
        @user = User.find_by_name(session[:user_name])
 
 if request.put?
params[:user].delete('name')
# params[:domain].delete('domain')

File.open("/opt/nginx/conf/website/#{@user.name}.conf", "w") do |file|
file.write(
   " server {
        listen       80;
        server_name   #{@user.domain} #{@user.domain2};

      location / {
        root   /home/#{@user.name}/www;

        access_log /root/#{@user.name}.log;
        error_log  /root/#{@user.name}.log;

        index  index.php index.html index.htm;
        }

       location ~ \.php$ {
            root   /home/#{@user.name}/www;
            index  index.php index.html index.htm;
            fastcgi_pass   127.0.0.1:9000;
            fastcgi_index  index.php;
        #    fastcgi_param  SCRIPT_FILEnAME  /scripts$fastcgi_script_name;
            fastcgi_param  SCRIPT_FILENAME  /home/#{@user.name}/www$fastcgi_script_name;
            fastcgi_param SCRIPT_NAME /home/#{@user.name}/www$fastcgi_script_name;
            include        fastcgi_params;
       }

    }
    ")
  end



   respond_to do |format|
     if @user.update_attributes(params[:user])
       format.html { redirect_to(users_path, :notice => '修改成功!') }
       format.xml  { head :ok }
     else
       format.html { render :action => "edit" }
       format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
     end
   end
 end


  end

  # def show
    
  # end

 
end

app/views/users/_error_messages.html.erb
<% if target.errors.any? %>
<div id="errorExplanation" style='color:red'>
  <h2><%= target.errors.count.to_s + "错误！"  %> </h2>
  <ul>
  <% target.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>

app/views/users/domain.html.erb
<div class="BodyContents">

  <div class="TitleArea">
    <h2> 用户信息修改</h2>
  </div>
  <div class="TitleArea">
  请填写正域名不要加   “／”　、  "http://"　或带有空格<br/>
如:
www.baidu.com
baidu.com
  </div>


  <!--  <br class="clear" />-->
  <div class="poststuff">
 <%= form_for @user, :url => domain_users_path, :html => {:multipart => true ,:id => 'form'} do |form| %>


  <div class="LeftNew">
    <div class="Inner">
    <%= render "error_messages", :target => @user %>
      <div class="AcceNew">


        <dl>
          <dt><%= controller_name.classify.constantize.human_attribute_name(:domain) %></dt>
          <dd>
            <%= form.text_field   :domain , :class => 'style1' %>
        </dl>
       <dl>
          <dt><%= controller_name.classify.constantize.human_attribute_name(:domain2) %></dt>
          <dd>
            <%= form.text_field   :domain2 , :class => 'style1' %>
        </dl>

 
      </div>
      <div class="PostBtn">
        <p>
          <%= form.submit t('labels.save')  , :class=>"btnW2_search" %>
        </p>
        <br class="clear" />
      </div>
    </div>
  </div>
<% end %>



</div>
</div>
 

app/views/users/edit.html.erb
<div class="BodyContents">
  <div class="TitleArea">
    <h2> 用户信息修改</h2>
  </div>
  <!--  <br class="clear" />-->
  <div class="poststuff">
 <%= form_for @user, :url => user_path(@user), :html => {:multipart => true ,:id => 'form'} do |form| %>
  <div class="LeftNew">
    <div class="Inner">

      <div class="AcceNew">

        <dl>
          <dt><%= controller_name.classify.constantize.human_attribute_name(:domain) %></dt>
          <dd>
            <%#= form.text_field   :domain , :class => 'style1' %>
            <%= @user.domain %>          <%= @user.domain2 %>
          </dd>
        </dl>
 

        <dl>
          <dt><%= controller_name.classify.constantize.human_attribute_name(:name) %></dt>
          <dd>
            <%#= form.text_field   :name , :class => 'style1' %>
             <%= @user.name %>
          </dd>
        </dl>


        <dl>
          <dt><%= controller_name.classify.constantize.human_attribute_name(:email) %></dt>
          <dd>
            <%= form.text_field   :email , :class => 'style1' %>
          </dd>
        </dl>


        <dl>
          <dt><%= controller_name.classify.constantize.human_attribute_name(:qq) %></dt>
          <dd>
            <%= form.text_field   :qq , :class => 'style1' %>
          </dd>
        </dl>

        <dl>
          <dt><%= controller_name.classify.constantize.human_attribute_name(:tel) %></dt>
          <dd>
            <%= form.text_field   :tel , :class => 'style1' %>
          </dd>
        </dl>


 
      </div>
      <div class="PostBtn">
        <p>
          <%= form.submit t('labels.save')  , :class=>"btnW2_search" %>
        </p>
        <br class="clear" />
      </div>
    </div>
  </div>
<% end %>



</div>
</div>
 

app/views/users/index.html.erb
 
<div class="BodyContents">
  <div class="TitleArea">
    <h2>用户信息</h2>

    <p class="btnW5"><%= link_to  '修改', edit_user_path(@user)  %></p>
  </div>
 
 
<div class="SumArea">
    <dl>
      <dt><%= User.human_attribute_name(:domain) %></dt>
      <dd> <%= @user.domain %>          <%= @user.domain2 %></dd>
    </dl>


        <dl>
          <dt><%= User.human_attribute_name(:name) %></dt>
          <dd><%= @user.name%></dd>
        </dl>

        <dl>
          <dt><%= User.human_attribute_name(:qq) %></dt>
          <dd><%= @user.qq%></dd>
        </dl>

        <dl>
          <dt><%= User.human_attribute_name(:email) %></dt>
          <dd><%= @user.email%></dd>
        </dl>

            <dl>
          <dt><%= User.human_attribute_name(:tel) %></dt>
          <dd><%= @user.tel%></dd>
        </dl>

 


  </div>
  </div>

</div>
 

app/views/users/new.html.erb
 
<!-- feed is cached -->
 <div class="BodyContents">
  <div class="TitleArea">
    <h2>用户信息修改</h2>
  </div>
  <!--  <br class="clear" />-->
  <div class="poststuff">
<%= form_for @user, :url => users_path, :html => {:multipart => true ,:id => 'form'} do |form| %>
  <div class="LeftNew">
    <div class="Inner">
  <%= render "error_messages", :target => @user %>
  <br/>
      <div class="AcceNew">
        <dl>
          <dt><%= User.human_attribute_name(:domain) %>(格式必须正确,如果没有可先写一个测试的随后改)</dt>
          <dd>
            <%= form.text_field   :domain , :class => 'style1' %>

          </dd>
        </dl>

        <dl>
          <dt><%= User.human_attribute_name(:name) %> (必须是５个以的字母组合)</dt>
          <dd>
            <%= form.text_field   :name , :class => 'style1' %>
 
          </dd>
        </dl>
        <dl>
          <dt><%= User.human_attribute_name(:password) %></dt>
          <dd>
            <%= form.text_field   :password , :class => 'style1' %>
          </dd>
        </dl>
        <dl>
          <dt><%= User.human_attribute_name(:password_confirmation) %></dt>
          <dd>
            <%= form.text_field   :password_confirmation , :class => 'style1' %>
          </dd>
        </dl>

      </div>
      <div class="PostBtn">
        <p>
          <%= form.submit '保存' , :class=>"btn2" %>
        </p>
        <br class="clear" />
      </div>
    </div>
  </div>
<% end %>
  </div>
</div>

app/views/users/password.html.erb
<div class="BodyContents">
  <div class="TitleArea">
    <h2> 用户信息修改</h2><br/>
    
  </div>
  <span style='color:red'>修改密码仅修改ssh ftp密码<span/>
  <!--  <br class="clear" />-->
  <div class="poststuff">
 <%= form_for @user, :url => password_users_path, :html => {:multipart => true ,:id => 'form'} do |form| %>
  <div class="LeftNew">
    <div class="Inner">

      <div class="AcceNew">

        <dl>
          <dt><%= controller_name.classify.constantize.human_attribute_name(:password) %></dt>
          <dd>
            <%= form.password_field   :password , :class => 'style1' %>
          </dd>
        </dl>
 
 
         <dl>
          <dt><%= controller_name.classify.constantize.human_attribute_name(:password_confirmation) %></dt>
          <dd>
            <%= form.password_field   :password_confirmation , :class => 'style1' %>
          </dd>
        </dl>
 

 
      </div>
      <div class="PostBtn">
        <p>
          <%= form.submit t('labels.save')  , :class=>"btnW2_search" %> 
        </p>
        <br class="clear" />
      </div>
    </div>
  </div>
<% end %>



</div>
</div>
 

app/views/users/show.html.erb
  <div class="LeftNew">
    <div class="Inner">
      <div class="AcceNew">
        <dl>
          <dt><%= User.human_attribute_name(:name) %></dt>
          <dd>
            <%= @user.name  %>
          </dd>
        </dl>
        <dl>
          <dt><%= User.human_attribute_name(:password) %></dt>
          <dd>
            <%= @user.password  %>
          </dd>
        </dl>
 
      </div>
 
    </div>
  </div>