config/routes.rb
Virturlmin::Application.routes.draw do
 
  mount Ckeditor::Engine => '/ckeditor'

  resources :users  do
      collection do
        get :domain
        put :domain
        get :password 
        put :password 
      end
    end

  resources :blogs

  resources :files   do
      collection do
        get :zip
        get :unzip
        get :logout
        post :setlocale
      end
    end
 resources :sessions do
      collection do
        get :home
        get :yinsi
        get :logout
        post :setlocale
      end
    end
  resources :tops do
        collection do
        get :resume
        get :logout
        post :setlocale
      end
  end
  namespace :admin do 
    match '/',:controller => 'sessions',:action => 'new'
    resources :sessions do
      collection do
        get :home
        get :logout
        post :setlocale
      end
    end
    resources :administrators
    resources :categories
    resources :blogs
    resources :links
    resources :pages
  end

  root :to => "sessions#new"

match '/files/master/*file' => 'files#index' , :constraints => { :file => /.*/  } , :format => false
match '/files/zip/*file' => 'files#zip' , :constraints => { :file => /.*/  } , :format => false
match '/files/unzip/*file' => 'files#unzip' , :constraints => { :file => /.*/  } , :format => false
end

app/views/shared/_left_banner.erb
  <div id="sidebar" class="col-2">
      <%  Category.root.each do |root| -%>
      <h4 style=" border-bottom: 0px solid #DEDEDE;"><%= root.name %></h4>
      <ul class="submenu" style=" border-top: 1px solid #DEDEDE;">
        <% root.children.each do |children| %>
          <li><a href="/blogs?category_id=<%= children.id %>"><%= children.name %></a></li>
        <% end %>
      </ul>
      <% end %>
    </div>

app/views/shared/_submenu.erb
<!--LEFT NAVI-->
<div class="LeftNavi">

  <div class="ListArea">
    <p class="Category">管理菜单</p>
    <ul>
      <li class="Level1 <%= 'current' if controller_name == 'administrators' %>">
        <a href='/users' class='l1'>用户信息</a>
          <ul class="Level2">
            <li class=" <%= (action_name=='edit'||action_name=='index')&& controller_name=='news' ? 'on' :'' %>">
              <%= link_to '用户基本信息', users_path %>
            </li>        
               <li class="">
              <%= link_to '域名修改', domain_users_path %>
            </li>        
                  <li class="">
              <%= link_to '密码修改', password_users_path %>
            </li>
            </li>
          </ul>
      </li>
    </ul>


    <ul>
      <li class="Level1">
        <a href='/files' class='l1'>文件管理</a> 
          <ul class="Level2">
            <li class=" <%= (action_name=='edit'||action_name=='index')&& controller_name=='news' ? 'on' :'' %>">
              <%= link_to '文件列表' ,  files_path %>
            </li>
            <li class="last <%= action_name=='new'&& controller_name=='news' ? 'on' :'' %>">
            <%= link_to '文件列表' ,  files_path %>
            </li>
          </ul> 
      </li>
    </ul>

<!--

    <ul>
      <li class="Level1 <%= 'current' if controller_name == 'administrators' %>">
        <a href='/users' class='l1'>咨询</a>
        <% if  ['administrators'].include?(controller_name) %>
          <ul class="Level2">
            <li class=" <%= (action_name=='edit'||action_name=='index')&& controller_name=='news' ? 'on' :'' %>">
              <%= link_to t('labels.manager', :model => Administrator.model_name.human), admin_administrators_path %>
            </li>
            <li class="last <%= action_name=='new'&& controller_name=='news' ? 'on' :'' %>">
              <%= link_to t('labels.add_manager', :model => Administrator.model_name.human), new_admin_administrator_path %>
            </li>
          </ul>
        <% end %>
      </li>
    </ul>


    <ul>
      <li class="Level1 <%= 'current' if controller_name == 'administrators' %>">
        <a href='/users' class='l1'>备份文件</a>
        <% if  ['administrators'].include?(controller_name) %>
          <ul class="Level2">
            <li class=" <%= (action_name=='edit'||action_name=='index')&& controller_name=='news' ? 'on' :'' %>">
              <%= link_to t('labels.manager', :model => Administrator.model_name.human), admin_administrators_path %>
            </li>
            <li class="last <%= action_name=='new'&& controller_name=='news' ? 'on' :'' %>">
              <%= link_to t('labels.add_manager', :model => Administrator.model_name.human), new_admin_administrator_path %>
            </li>
          </ul>
        <% end %>
      </li>
    </ul>




    <ul>
      <li class="Level1 <%= 'current' if controller_name == 'administrators' %>">
        <a href='/users' class='l1'>备份数据库存</a>
        <% if  ['administrators'].include?(controller_name) %>
          <ul class="Level2">
            <li class=" <%= (action_name=='edit'||action_name=='index')&& controller_name=='news' ? 'on' :'' %>">
              <%= link_to t('labels.manager', :model => Administrator.model_name.human), admin_administrators_path %>
            </li>
            <li class="last <%= action_name=='new'&& controller_name=='news' ? 'on' :'' %>">
              <%= link_to t('labels.add_manager', :model => Administrator.model_name.human), new_admin_administrator_path %>
            </li>
          </ul>
        <% end %>
      </li>
    </ul>

-->

  </div>
</div>