config/routes.rb
Virturlmin::Application.routes.draw do
 
  mount Ckeditor::Engine => '/ckeditor'

  resources :users  do
      collection do
        get :domain
        put :domain
        get :password 
        put :password 
      end
    end

  resources :blogs

  resources :files   do
      collection do
        get :zip
        get :unzip
        get :logout
        post :setlocale
      end
    end
 resources :sessions do
      collection do
        get :home
        get :yinsi
        get :logout
        post :setlocale
      end
    end
  resources :tops do
        collection do
        get :resume
        get :logout
        post :setlocale
      end
  end
  namespace :admin do 
    match '/',:controller => 'sessions',:action => 'new'
    resources :sessions do
      collection do
        get :home
        get :logout
        post :setlocale
      end
    end
    resources :administrators
    resources :categories
    resources :blogs
    resources :links
    resources :pages
  end

  root :to => "sessions#new"

match '/files/master/*file' => 'files#index' , :constraints => { :file => /.*/  } , :format => false
match '/files/zip/*file' => 'files#zip' , :constraints => { :file => /.*/  } , :format => false
match '/files/unzip/*file' => 'files#unzip' , :constraints => { :file => /.*/  } , :format => false
end

app/controllers/files_controller.rb
# coding: UTF-8
class FilesController < ApplicationController
  before_filter :user_authorize
  layout 'users'
  # GE: /blogs
  # GET /blogs.xml
  def index
 
 

    if params[:file]
      @file =  params[:file] 
      p @file
      @path = "/home/session[:user_name]/#{@file}"
      @path.to_s.gsub!('\.\.' , '')
      if File.directory?(@path)
       @files =  Dir.foreach("/home/session[:user_name]/#{@file}") 
      else
       send_file         @path
      end
    else
      @path = "/home/session[:user_name]"
      @files =  Dir.foreach("/home/session[:user_name]")
    
    end


   
  end


def zip

    if params[:file]
      @file =  params[:file] 
      @path = "/home/session[:user_name]/#{@file}"
    else
      @path = "/home/session[:user_name]"
    end
     @path.to_s.gsub!('\.\.' , '')
     p system(" tar czf #{@path}.tar.gz  #{@path}  ")
     # p system(" chown -R session[:user_name]:session[:user_name]   /home/session[:user_name]/")
     redirect_to "#{files_path}/master/#{@file}/.."
end


def unzip


    if params[:file]
      @file =  params[:file] 
      @path = "/home/session[:user_name]/#{@file}"
    else
      @path = "/home/session[:user_name]"
    end
    if params[:f]
      @d =  params[:f] 
      @directory = "/home/session[:user_name]/#{@d}"
    else
      @directory = "/home/session[:user_name]"
    end


     @path.to_s.gsub!('\.\.' , '')
     @directory.to_s.gsub!('\.\.' , '')

     if @path.include?(".tar")
     p system("  tar xvf #{@path}  -C  #{@directory}  ")
     end
    if @path.include?(".zip")
     p system(" unzip #{@path}  -d  #{@directory}  ")
     end
     # p system(" chown -R session[:user_name]:session[:user_name]   /home/session[:user_name]/")
     redirect_to "#{files_path}/master/#{@file}/.."
  
end


def create

        @path = "/home/session[:user_name]/#{params[:file]}"
        @path.to_s.gsub!('\.\.' , '')
        @path.to_s.gsub!(/\/\// , '/')
      # ic = Iconv.new('GBK//IGNORE', 'UTF-8')
    # user =   File.open("#{RAILS_ROOT}/#{file}.xls" ,'w+')
    # user.write(params[:file].read)
    # user.close
# f = File.open("#{@path}/#{params[:filedata].original_filename}", "w+")
 # f.write(Iconv.iconv(  'gbk','utf-8',   params[:filedata].read) ) 
 unless  params[:filedata].blank?
f = File.open("#{@path}/#{params[:filedata].original_filename}", "wb")
f.write( params[:filedata].read) 
f.close
end

 redirect_to "#{files_path}/#{params[:file]}"

end


  def show
 

      @path = "/home/session[:user_name]/#{params[:file]}"
      @files =  Dir.foreach("/home/session[:user_name]/#{params[:file]}") 

        render :index
   
  end
end

app/views/files/index.html.erb
<style>
.ListContents td.Blue {
background: #F1F1F1;
padding: 3px;
text-align: left;
}
.ListContents td{
  padding: 3px;
}
</style>
<div class="BodyContents">
  <div class="TitleArea">
    <h2>文件管理</h2>

  </div>


<%=  link_to '根目录' , "#{files_path}/master"%>


<%=  link_to '上一级' , "#{files_path}/master#{show_directory(params[:file])}/.."%>

    <div class="SearchArea2">
      <p class="title">
<%= form_tag  files_path , :multipart => true ,:id => 'form' do   %>

<%= file_field_tag :filedata%>
<%= text_field_tag :file,params[:file], :class => "typeA" ,:style=>'width:300px' %>

     
          <%=  submit_tag '上传'  , :class=>"BottomW2" %>

<% end %>
      </p>
    </div>



  <!--LIST-->
  <div class="ListContents">
   
   <% if File.directory?(@path)  %>


    <table cellspacing="0" cellpadding="0" border="0" class="widefat">
      <tbody>

      <tr>
        <th class="lineB " scope="col">
           文件名
        </th>
        <th class="lineB " scope="col">
  文件类型
        </th>
          <th class="lineB operation-column" scope="col">操作</th>
        <th class="lineB operation-column" scope="col">打包</th>
      </tr>
 


 <%     @files.each  do |file| %>
          <%unless   ['.','..'].include?(file)%>
          <% if File.directory?("#{@path}/#{file}") %>
          <%- cycle_class = cycle('Blue', '') %>
          <tr>
            <td class="<%= cycle_class %>"><%= file%></td>
            <td class="<%= cycle_class %>">文件夹</td>
             <td class="<%= cycle_class %>"><%=  link_to '打开' , "#{files_path}/master#{show_directory(params[:file])}/#{file}"%></td>
             <td class="<%= cycle_class %>"><%=  link_to '打包' , "#{zip_files_path}#{show_directory(params[:file])}/#{file}"%></td>
          </tr>
          <%end%>
          <%end%>

<%end%>
 <%     @files.each  do |file| %>

          <% unless File.directory?("#{@path}/#{file}") %>
                    <%- cycle_class = cycle('Blue', '') %>
          <tr>
            <td class="<%= cycle_class %>"><%= file%></td>
            <td class="<%= cycle_class %>">文件</td>
            <td class="<%= cycle_class %>"><%=  link_to '下载' , "#{files_path}/master#{show_directory(params[:file])}/#{file}"%></td>
          <td class="<%= cycle_class %>">
<% if file.include?(".zip") || file.include?(".tar")%>
<%=  link_to '解压' , "#{unzip_files_path}#{show_directory(params[:file])}/#{file}?f=#{params[:file]}"%>
<%end%>

          </td>
          </tr>
          <%end%>

<%end%>
      <tr>
        <th class="lineB " scope="col">
           文件名
        </th>
        <th class="lineB " scope="col">
  文件类型
        </th>
          <th class="lineB operation-column" scope="col">操作</th>
        <th class="lineB operation-column" scope="col">打包</th>
      </tr>
 
      </tbody>
    </table>

   <%else%>
<%
require 'iconv'

ic = Iconv.new('GBK//IGNORE', 'UTF-8')

%>

<% File.open(@path , "r") do |f|%>
<code><pre>
<%#= raw  Iconv.iconv( 'utf-8',  'gbk', f.read)  %>
<%= text_area_tag 'post' ,Iconv.iconv( 'utf-8',  'gbk', CGI::escape(f.read)), :rows => 110, :cols => 125 %>

</pre></code>
<%end%>
<%end%>
  </div>

</div>

app/views/files/show.html.erb
<div class="BodyContents">
  <div class="TitleArea">
    <h2>文件管理</h2>

  </div>


  <!--LIST-->
  <div class="ListContents">
    <table cellspacing="0" cellpadding="0" border="0" class="widefat">
      <tbody>

      <tr>
        <th class="lineB " scope="col">
           文件名
        </th>
        <th class="lineB " scope="col">
  文件类型
        </th>
  
        <th class="lineB operation-column" scope="col">操作</th>
      </tr>
 


 <%     @files.each  do |file| %>

          <% if File.directory?(@path) %>
                    <%- cycle_class = cycle('Blue', '') %>
          <tr>
            <td class="<%= cycle_class %>"><%= file%></td>
            <td class="<%= cycle_class %>">文件夹</td>
             <td class="<%= cycle_class %>"><%=  link_to 'dakai' , "#{files_path}#{params[:file]}/#{file}"%></td>
            <td class="<%= cycle_class %>">

              <br/>
            </td>
          </tr>
          <%end%>

<%end%>
 <%     @files.each  do |file| %>

          <% unless File.directory?(@path) %>
                    <%- cycle_class = cycle('Blue', '') %>
          <tr>
            <td class="<%= cycle_class %>"><%= file%></td>
            <td class="<%= cycle_class %>">文件</td>
            <td class="<%= cycle_class %>">

              <br/>
            </td>
          </tr>
          <%end%>

<%end%>
      <tr>
        <th class="lineB " scope="col">
           文件名
        </th>
        <th class="lineB " scope="col">
  文件类型
        </th>
  
        <th class="lineB operation-column" scope="col">操作</th>
      </tbody>
    </table>


  </div>

</div>