config/routes.rb
Virturlmin::Application.routes.draw do
 
  mount Ckeditor::Engine => '/ckeditor'

  resources :users  do
      collection do
        get :domain
        put :domain
        get :password 
        put :password 
      end
    end

  resources :blogs

  resources :files   do
      collection do
        get :zip
        get :unzip
        get :logout
        post :setlocale
      end
    end
 resources :sessions do
      collection do
        get :home
        get :yinsi
        get :logout
        post :setlocale
      end
    end
  resources :tops do
        collection do
        get :resume
        get :logout
        post :setlocale
      end
  end
  namespace :admin do 
    match '/',:controller => 'sessions',:action => 'new'
    resources :sessions do
      collection do
        get :home
        get :logout
        post :setlocale
      end
    end
    resources :administrators
    resources :categories
    resources :blogs
    resources :links
    resources :pages
  end

  root :to => "sessions#new"

match '/files/master/*file' => 'files#index' , :constraints => { :file => /.*/  } , :format => false
match '/files/zip/*file' => 'files#zip' , :constraints => { :file => /.*/  } , :format => false
match '/files/unzip/*file' => 'files#unzip' , :constraints => { :file => /.*/  } , :format => false
end

app/views/admin/shared/_errors.erb
      <%=   model.errors.full_messages.join("<br/>").html_safe  %>
      <br/>

app/views/admin/shared/_notice.erb
<% if flash[:notice] %>
    <div class="MessageBox">
      <p><%= flash[:notice] %></p>
    </div>
<% end %>

app/views/admin/shared/_paginate.erb
<div class="section2">
  <div class="PageArea">
    <% unless objects.blank? %>
        <%= paginate(objects) %>
        <%=  raw "<span class='info'>当前显示 #{(objects.current_page - 1) * objects.limit_value + 1 }-  #{(objects.current_page - 1) * objects.limit_value + objects.count } 条，共#{objects.total_count}条</span>" %>
    <% end %> 
  </div>
</div>

app/views/admin/shared/_paginate_not_delete.erb
<div class="section2">
  <div class="OperationArea">
    <!--
    <a class="batch delselect_all" href="javascript:void(0)"><%= t('labels.delete_select') %></a>
    -->
  </div>
  <div class="OperationArea">
    <% unless objects.blank? %>
      <%= paginate(objects) %>
      <%=  raw "<span class='info'>当前显示 #{(objects.current_page - 1) * objects.limit_value + 1 }-  #{(objects.current_page - 1) * objects.limit_value + objects.count } 条，共#{objects.total_count}条</span>" %>
    <% end %>
  </div>
</div>

app/views/admin/shared/_submenu.erb
<!--LEFT NAVI-->
<div class="LeftNavi">

  <div class="ListArea">
    <p class="Category"><%= t("h2.session_home") %></p>
    <ul>
      <li class="Level1 <%= 'current' if controller_name == 'administrators' %>"><%= link_to t('labels.manager', :model => Administrator.model_name.human), admin_administrators_path, :class => "l1" %>
        <% if  ['administrators'].include?(controller_name) %>
          <ul class="Level2">
            <li class=" <%= (action_name=='edit'||action_name=='index')&& controller_name=='news' ? 'on' :'' %>">
              <%= link_to t('labels.manager', :model => Administrator.model_name.human), admin_administrators_path %>
            </li>
            <li class="last <%= action_name=='new'&& controller_name=='news' ? 'on' :'' %>">
              <%= link_to t('labels.add_manager', :model => Administrator.model_name.human), new_admin_administrator_path %>
            </li>
          </ul>
        <% end %>
      </li>
      <li class="Level1 <%= 'current' if controller_name == 'blogs' %>"><%= link_to t('labels.manager', :model => Blog.model_name.human), admin_blogs_path, :class => "l1" %>
        <% if  ['blogs'].include?(controller_name) %>
          <ul class="Level2">
            <li class=" <%= (action_name=='edit'||action_name=='index')&& controller_name=='news' ? 'on' :'' %>">
              <%= link_to t('labels.manager', :model => Blog.model_name.human), admin_blogs_path %>
            </li>
            <li class="last <%= action_name=='new'&& controller_name=='news' ? 'on' :'' %>">
              <%= link_to t('labels.add_manager', :model => Blog.model_name.human), new_admin_blog_path %>
            </li>
          </ul>
        <% end %>
      </li>
      <li class="Level1 <%= 'current' if controller_name == 'categories' %>"><%= link_to t('labels.manager', :model => Category.model_name.human), admin_categories_path, :class => "l1" %>
        <% if  ['categories'].include?(controller_name) %>
          <ul class="Level2">
            <li class=" <%= (action_name=='edit'||action_name=='index')&& controller_name=='news' ? 'on' :'' %>">
              <%= link_to t('labels.manager', :model => Category.model_name.human), admin_categories_path %>
            </li>
            <li class="last <%= action_name=='new'&& controller_name=='news' ? 'on' :'' %>">
              <%= link_to t('labels.add_manager', :model => Category.model_name.human), new_admin_category_path %>
            </li>
          </ul>
        <% end %>
      </li>



      <li class="Level1 <%= 'current' if controller_name == 'links' %>"><%= link_to t('labels.manager', :model => Link.model_name.human), admin_links_path, :class => "l1" %>
        <% if  ['categories'].include?(controller_name) %>
          <ul class="Level2">
            <li class=" <%= (action_name=='edit'||action_name=='index')&& controller_name=='links' ? 'on' :'' %>">
              <%= link_to t('labels.manager', :model => Link.model_name.human), admin_links_path %>
            </li>
            <li class="last <%= action_name=='new'&& controller_name=='links' ? 'on' :'' %>">
              <%= link_to t('labels.add_manager', :model => Link.model_name.human), new_admin_link_path %>
            </li>
          </ul>
        <% end %>
      </li>



      <li class="Level1 <%= 'current' if controller_name == 'pages' %>"><%= link_to '网站静态页面', admin_pages_path, :class => "l1" %>
        <% if  ['pages'].include?(controller_name) %>
        <ul class="Level2">

          <% Page.all.each do |page|  %>
            <li class="">
              <%= link_to page.name, edit_admin_page_path(page) %>
            </li>
          <% end %>
          <li class="last">
            <%= link_to "添加模块", new_admin_page_path %>
          </li>
        </ul>
        <% end %>
      </li>




    </ul>
  </div>
</div>